version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model:/model 
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped